default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: postgres
  password: newpassword
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: PostDb

test:
  <<: *default
  database: PostTestDb

production:
  <<: *default
  database: PostProductionDb
  username: postgres   
  password: newpassword
